CREATE DATABASE QLCUOCTHIHAT
USE QLCUOCTHIHAT

-- UPDATED: 10/04/2019

--PHẦN 1:TẠO CƠ SỞ DỮ LIỆU TRÊN SQL SERVER
--BẢNG 1
CREATE TABLE NGUOI(
ID CHAR(12) PRIMARY KEY,
CMND CHAR(15) NOT NULL,
TEN NVARCHAR(20) NOT NULL,
GIOITINH INT CHECK(GIOITINH = 1 OR GIOITINH = 0) NOT NULL,
NGAYSINH DATE NOT NULL,
NOISINH NVARCHAR(20) NOT NULL,
CHECK(ID LIKE '[T][S][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'
   OR ID LIKE '[N][S][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]')
)
GO

-- BẢNG 2
CREATE TABLE THISINH(
MATHISINH CHAR(12) PRIMARY KEY,
DIACHI NVARCHAR(20) NOT NULL,
DIENTHOAI INT NOT NULL,
GIOITHIEU NVARCHAR(MAX),
FOREIGN KEY(MATHISINH) REFERENCES NGUOI(ID) ON UPDATE CASCADE ON DELETE CASCADE,
CHECK(MATHISINH LIKE '[TS][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]')
)
GO
--BẢNG 3
CREATE TABLE NGHESI(
MANGHESI CHAR(12) PRIMARY KEY,
NGHEDANH NVARCHAR(20) NOT NULL,
THANHTICH NVARCHAR(MAX) NOT NULL,
MCFlag INT CHECK(MCFlag = 0 OR MCFlag = 1),
CSFlag INT CHECK(CSFlag = 0 OR CSFlag = 1),
NSFlag INT CHECK(NSFlag = 0 OR NSFlag = 1),
FOREIGN KEY(MANGHESI) REFERENCES NGUOI(ID) ON UPDATE CASCADE ON DELETE CASCADE,
CHECK(MANGHESI LIKE '[NS][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]')
)
GO

--BẢNG 4
CREATE TABLE MC(
MAMC CHAR(12) NOT NULL,
CHUONGTRINHDADAN NVARCHAR(20),
PRIMARY KEY(MAMC, CHUONGTRINHDADAN),
FOREIGN KEY(MAMC) REFERENCES NGHESI(MANGHESI) ON UPDATE CASCADE ON DELETE CASCADE,
-- Thêm cột mã mùa thi
)

GO

--BẢNG 5
CREATE TABLE ALBUMCS(
MACS CHAR(12) NOT NULL,
ALBUM NVARCHAR(20) NOT NULL,
PRIMARY KEY(MACS, ALBUM),
FOREIGN KEY(MACS) REFERENCES NGHESI(MANGHESI) ON UPDATE CASCADE ON DELETE CASCADE,
)
GO
--BẢNG 6
CREATE TABLE BAIHAT(
MABAIHAT CHAR(8) PRIMARY KEY,
TUABAIHAT NVARCHAR(20) NOT NULL,
CHECK(MABAIHAT LIKE '[BH][0-9][0-9][0-9][0-9][0-9][0-9]')
)
GO


--BẢNG 7
CREATE TABLE THELOAI(
MATHELOAI CHAR(5) PRIMARY KEY,
TENTHELOAI NVARCHAR(20) NOT NULL UNIQUE,
CHECK(MATHELOAI LIKE '[TL][0-9][0-9][0-9]')
)
GO
--BẢNG 8
CREATE TABLE BAIHATTHELOAI(
MABAIHAT CHAR(8) FOREIGN KEY REFERENCES BAIHAT(MABAIHAT),
MATHELOAI CHAR(5) FOREIGN KEY REFERENCES THELOAI(MATHELOAI),
PRIMARY KEY(MABAIHAT,MATHELOAI)
)
GO


--BẢNG 9
CREATE TABLE NHACSISANGTAC(
MANS CHAR(12) FOREIGN KEY REFERENCES NGHESI(MANGHESI),
MABAIHAT CHAR(8) FOREIGN KEY REFERENCES BAIHAT(MABAIHAT),
THONGTINSANGTAC INT NOT NULL,
CHECK (THONGTINSANGTAC = 1 OR THONGTINSANGTAC = 2 OR THONGTINSANGTAC = 3),
PRIMARY KEY(MANS,MABAIHAT)
)
GO

--BẢNG 10
CREATE TABLE TINHTHANH(
MATINHTHANH CHAR(4) PRIMARY KEY,
TENTINHTHANH NVARCHAR(20) NOT NULL UNIQUE,
CHECK(MATINHTHANH LIKE '[TT][0-9][0-9]')
)
GO

--BẢNG 11
CREATE TABLE NHASANXUAT(
MANSX CHAR(6) PRIMARY KEY,
TENNSX NVARCHAR(20) NOT NULL,
CHECK(MANSX LIKE '[NSX][0-9][0-9][0-9]')
)
GO

--BẢNG 12
CREATE TABLE KENHTRUYENHINH(
MAKTH CHAR(6) PRIMARY KEY,
TENKENH NVARCHAR(20) NOT NULL,
CHECK(MAKTH LIKE '[TH][0-9][0-9][0-9]')
)
GO


------------------HÀM TỰ ĐỘNG TĂNG CHO ID MÙA THI------------------------
CREATE FUNCTION AUTO_IDMT()
RETURNS CHAR(4)
AS
BEGIN
	DECLARE @ID CHAR(4)
	IF (SELECT COUNT(MAMUATHI) FROM MUATHI) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MAMUATHI, 2)) FROM MUATHI
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'MT0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'MT' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END
----------------------------------------------------------
GO

--BẢNG 13
CREATE TABLE MUATHI (
MAMUATHI CHAR(4) PRIMARY KEY DEFAULT DBO.AUTO_IDMT(),
NGAYBD DATE,
NGAYKT DATE,
GIAITHUONG NVARCHAR(MAX),
DIADIEMNHAHAT NVARCHAR(50),
DIADIEMBANKET NVARCHAR(50),
DIADIEMGALA NVARCHAR(50),
MABAIHAT CHAR(8),
MAGIAMDOC CHAR(12) UNIQUE,
GIAMKHAO1 CHAR(12) UNIQUE,
GIAMKHAO2 CHAR(12) UNIQUE,
GIAMKHAO3 CHAR(12) UNIQUE,
MAMC CHAR(12) UNIQUE,
CHECK(NGAYKT > NGAYBD),
)
GO

-- Cần thêm cột mã mùa thi vào 2 bảng: MC, NHACSISANGTAC
--ALTER TABLE MC ADD MAMUATHI CHAR(4)
--ALTER TABLE MC ADD CONSTRAINT FK_MUATHI_MAMUATHI_MC FOREIGN KEY(MAMUATHI) REFERENCES MUATHI(MAMUATHI)
--------------------------------------------------------------
--ALTER TABLE MUATHI ADD CONSTRAINT FK_MUATHI_MC_MC FOREIGN KEY(MAMC, CHUONGTRINHDADAN) REFERENCES MC(MAMC, CHUONGTRINHDADAN)



--BẢNG 14
CREATE TABLE BANQUYENMT(
MAMT CHAR(4),
MANSX CHAR(6),
PRIMARY KEY(MAMT, MANSX),
FOREIGN KEY(MAMT) REFERENCES MUATHI(MAMUATHI),
FOREIGN KEY(MANSX) REFERENCES NHASANXUAT(MANSX)
)

-- BẢNG 15
CREATE TABLE PHATSONG(
MAMT CHAR(4),
MAKENH CHAR(6),
THONGTINPHATSONG INT,
PRIMARY KEY(MAMT, MAKENH),
FOREIGN KEY(MAMT) REFERENCES MUATHI(MAMUATHI),
FOREIGN KEY(MAKENH) REFERENCES KENHTRUYENHINH(MAKTH)
)

-- BẢNG 16
CREATE TABLE VONGTHI(
STTVT INT IDENTITY(1,1),
MAMT CHAR(4),
TENVT NVARCHAR(20),
THOIGIANBD DATETIME,
THOIGIANKT DATETIME,
LOAIVT INT NOT NULL,
CHECK (THOIGIANBD < THOIGIANKT),
PRIMARY KEY(STTVT, MAMT),
FOREIGN KEY(MAMT) REFERENCES MUATHI(MAMUATHI),
)
GO

--BẢNG 17
CREATE TABLE THISINHTHAMGIA(
STTVT INT,
MAMT CHAR(4),
MATHISINH CHAR(12),
KETQUA INT DEFAULT -1,
PRIMARY KEY(STTVT, MAMT, MATHISINH),
FOREIGN KEY(STTVT, MAMT) REFERENCES VONGTHI(STTVT, MAMT),
FOREIGN KEY(MATHISINH) REFERENCES THISINH(MATHISINH),
)


--BẢNG 18
CREATE TABLE VONGTHUGIONG(
STTVT INT,
MAMT CHAR(4),
MATINH CHAR(4),
DIADIEM NVARCHAR(50),
PRIMARY KEY(STTVT, MAMT),
FOREIGN KEY(STTVT, MAMT) REFERENCES VONGTHI(STTVT, MAMT),
)

-- BẢNG 19
CREATE TABLE TSTHAMGIATHUVONG(
STTVT INT,
MAMT CHAR(4),
MATHISINH CHAR(12),
GK1 INT NOT NULL,
GK2 INT NOT NULL,
GK3 INT NOT NULL,
PRIMARY KEY(STTVT, MAMT, MATHISINH),
FOREIGN KEY(MATHISINH) REFERENCES THISINH(MATHISINH),
FOREIGN KEY(STTVT, MAMT) REFERENCES VONGTHUGIONG(STTVT, MAMT),
CHECK(GK1=1 OR GK1=0),
CHECK(GK2=1 OR GK2=0),
CHECK(GK3=1 OR GK3=0),
)

-- BẢNG 20
CREATE TABLE TSHATVONGTHUGIONG(
STTVT INT,
MAMT CHAR(4),
MATHISINH CHAR(12),
MABAIHAT CHAR(8),
PRIMARY KEY(STTVT, MAMT, MATHISINH, MABAIHAT),
FOREIGN KEY(MABAIHAT) REFERENCES BAIHAT(MABAIHAT),
FOREIGN KEY(MATHISINH) REFERENCES THISINH(MATHISINH),
FOREIGN KEY(STTVT, MAMT) REFERENCES VONGTHUGIONG(STTVT, MAMT),
)

-- BẢNG 21
CREATE TABLE VONGNHAHAT(
STTVT INT,
MAMT CHAR(4),
HATNHOMFLAG INT,
CHECK(HATNHOMFLAG=0 OR HATNHOMFLAG=1),
PRIMARY KEY(STTVT, MAMT),
FOREIGN KEY(STTVT, MAMT) REFERENCES VONGTHI(STTVT, MAMT),
)

-- BẢNG 22
CREATE TABLE TSHATVONGNHAHAT(
STTVT INT,
MAMT CHAR(4),
MATHISINH CHAR(12),
MABAIHAT CHAR(8),
PRIMARY KEY(STTVT, MAMT, MATHISINH, MABAIHAT),
FOREIGN KEY(MATHISINH) REFERENCES THISINH(MATHISINH),
FOREIGN KEY(STTVT, MAMT) REFERENCES VONGNHAHAT(STTVT, MAMT),
FOREIGN KEY(MABAIHAT) REFERENCES BAIHAT(MABAIHAT),
)

-- BẢNG 23
CREATE TABLE NHOMCA(
MANHOM CHAR(8),
TENNHOM NVARCHAR(50),
MATHISINH1 CHAR(12) NOT NULL UNIQUE,
MATHISINH2 CHAR(12) NOT NULL UNIQUE,
MATHISINH3 CHAR(12) NOT NULL UNIQUE,
MATHISINH4 CHAR(12) NOT NULL UNIQUE,
PRIMARY KEY(MANHOM),
CHECK(MANHOM LIKE '[NC][0-9][0-9][0-9][0-9][0-9][0-9]'),
)

-- BẢNG 24
CREATE TABLE BAIHATNHOMCA(
MANHOM CHAR(8),
MABAIHAT CHAR(8),
STTVT INT,
MAMT CHAR(4),
PRIMARY KEY(MANHOM, MABAIHAT),
FOREIGN KEY(MANHOM) REFERENCES NHOMCA(MANHOM),
FOREIGN KEY(MABAIHAT) REFERENCES BAIHAT(MABAIHAT),
FOREIGN KEY(STTVT, MAMT) REFERENCES VONGNHAHAT(STTVT, MAMT),
)

-- BẢNG 25
CREATE TABLE VONGBANKET(
STTVT INT,
MAMT CHAR(4),
NAM_NU INT DEFAULT -1,
PRIMARY KEY(STTVT, MAMT),
FOREIGN KEY(STTVT, MAMT) REFERENCES VONGTHI(STTVT, MAMT),
CHECK(NAM_NU=1 OR NAM_NU=0),
)

-- BẢNG 26
CREATE TABLE TSTHAMGIABANKET(
STTVT INT,
MAMT CHAR(4),
MATHISINH CHAR(12),
MSBC CHAR(10) NOT NULL,
TONGTINNHAN INT NOT NULL,
PRIMARY KEY(STTVT, MAMT, MATHISINH),
FOREIGN KEY(STTVT, MAMT) REFERENCES VONGBANKET(STTVT, MAMT),
FOREIGN KEY(MATHISINH) REFERENCES THISINH(MATHISINH),
)

-- BẢNG 27
CREATE TABLE TSHATVONGBANKET(
MATHISINH CHAR(12),
MABAIHAT CHAR(8),
STTVT INT,
MAMT CHAR(4),
PRIMARY KEY(MATHISINH, MABAIHAT),
FOREIGN KEY(MATHISINH) REFERENCES THISINH(MATHISINH),
FOREIGN KEY(MABAIHAT) REFERENCES BAIHAT(MABAIHAT),
FOREIGN KEY(STTVT, MAMT) REFERENCES VONGBANKET(STTVT, MAMT),
)

-- BẢNG 28
CREATE TABLE VONGGALA(
STTVT INT,
MAMT CHAR(4),
CHUDE NVARCHAR(50) NOT NULL UNIQUE,
MANGUOIHD CHAR(12),
PRIMARY KEY(STTVT, MAMT),
SONGCAFLAG INT CHECK(SONGCAFLAG=1 OR SONGCAFLAG=0),
FOREIGN KEY(MANGUOIHD) REFERENCES NGHESI(MANGHESI),
FOREIGN KEY(STTVT, MAMT) REFERENCES VONGTHI(STTVT, MAMT),
)

-- BẢNG 29
CREATE TABLE TSTHAMGIAVONGGALA(
STTVT INT,
MAMT CHAR(4),
MATHISINH CHAR(12),
MSBC CHAR(10) NOT NULL,
TONGTINNHAN INT NOT NULL,
PRIMARY KEY(STTVT, MAMT, MATHISINH),
FOREIGN KEY(STTVT, MAMT) REFERENCES VONGGALA(STTVT, MAMT),
FOREIGN KEY(MATHISINH) REFERENCES THISINH(MATHISINH),
)

-- BẢNG 30
CREATE TABLE TSHATGALA(
MATHISINH CHAR(12),
MABAIHAT CHAR(8),
STTVT INT,
MAMT CHAR(4),
PRIMARY KEY(MATHISINH, MABAIHAT),
FOREIGN KEY(MATHISINH) REFERENCES THISINH(MATHISINH),
FOREIGN KEY(MABAIHAT) REFERENCES BAIHAT(MABAIHAT),
FOREIGN KEY(STTVT, MAMT) REFERENCES VONGGALA(STTVT, MAMT),
)



-- TẠO INDEX
-- CHỈ MỤC TRUY CẬP THÔNG TIN VÒNG THI DỰA VÀO TÊN VÒNG THI
CREATE INDEX INFOVONGTHI
ON VONGTHI (TENVT);
-- CHỈ MỤC THÔNG TIN THÍ SINH DỰA VÀO CHỨNG MINH THƯ

CREATE INDEX INFOTS
ON NGUOI (CMND);

INSERT INTO NGUOI VALUES('TS2019200001', '025711690', N'Đỗ Duy Thịnh', 1, '08/24/1999', 'TPHCM'),
						('NS2019200001', '025745691', N'Đỗ Duy Thiẹn', 1, '05/05/2010', 'TPHCM')

SELECT *
FROM NGUOI 
WITH(INDEX(INFOTS))
WHERE ID LIKE 'TS%'

-- THÔNG TIN MÙA GIẢI DỰA TRÊN NGÀY THÁNG NĂM BẮT ĐẦU
