CREATE DATABASE ASSIGNMENT1
USE ASSIGNMENT1

--PHẦN 1:TẠO CƠ SỞ DỮ LIỆU TRÊN SQL SERVER
--BẢNG 1
CREATE TABLE NGUOI(
ID CHAR(15) PRIMARY KEY,
CMND CHAR(15) NOT NULL,
TEN NVARCHAR(20) NOT NULL,
GIOITINH INT CHECK(GIOITINH = 1 OR GIOITINH = 0) NOT NULL,
NGAYSINH DATE NOT NULL,
NOISINH NVARCHAR(20) NOT NULL,
CHECK(ID LIKE '[TS|NS][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]')
)

-- BẢNG 2
CREATE TABLE THISINH(
MATHISINH CHAR(15) PRIMARY KEY,
DIACHI NVARCHAR(20) NOT NULL,
DIENTHOAI INT NOT NULL,
GIOITHIEU NVARCHAR(MAX),
CONSTRAINT FK_TS_ID_NGUOI FOREIGN KEY(MATHISINH) REFERENCES NGUOI(ID) ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT CK_TS_ID_NGUOI CHECK(MATHISINH LIKE '[TS][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]')
)

--BẢNG 3
CREATE TABLE NGHESI(
MANGHESI CHAR(15) PRIMARY KEY,
NGHEDANH NVARCHAR(20) NOT NULL,
THANHTICH NVARCHAR(MAX) NOT NULL,
MCFlag INT CHECK(MCFlag = 0 OR MCFlag = 1),
CSFlag INT CHECK(CSFlag = 0 OR CSFlag = 1),
NSFlag INT CHECK(NSFlag = 0 OR NSFlag = 1),
CONSTRAINT FK_NS_ID_NGUOI FOREIGN KEY(MANGHESI) REFERENCES NGUOI(ID) ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT CK_NS_ID_NGUOI CHECK(MANGHESI LIKE '[NS][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]')
)

--BẢNG 4
CREATE TABLE CHUONGTRINHMC(
MAMC CHAR(15) NOT NULL,
CHUONGTRINHDADAN NVARCHAR(20),
CONSTRAINT PK_MAMC_CTDAN PRIMARY KEY(MAMC, CHUONGTRINHDADAN),
CONSTRAINT FK_CTMC_MAMC_ID FOREIGN KEY(MAMC) REFERENCES NGHESI(MANGHESI) ON UPDATE CASCADE ON DELETE CASCADE,
)

----------------------------------------------------------------






--BẢNG 5
CREATE TABLE ALBUMCS(
MACS CHAR(15) PRIMARY KEY FOREIGN KEY REFERENCES NGHESI(MANGHESI),
ALBUM NVARCHAR(20),)
--BẢNG 6
CREATE TABLE BAIHAT(
MABAIHAT CHAR(15) PRIMARY KEY,
TUABAIHAT NVARCHAR(20) NOT NULL,)
--BẢNG 7
CREATE TABLE THELOAI(
MATHELOAI CHAR(15) PRIMARY KEY,
TENTHELOAI NVARCHAR(20) NOT NULL UNIQUE)
--BẢNG 8
CREATE TABLE BAIHATTHELOAI(
MABAIHAT CHAR(15) FOREIGN KEY REFERENCES BAIHAT(MABAIHAT),
MATHELOAI CHAR(15) FOREIGN KEY REFERENCES THELOAI(MATHELOAI),
PRIMARY KEY(MABAIHAT,MATHELOAI))
--BẢNG 9
CREATE TABLE NSSANGTAC(
MANS CHAR(15) FOREIGN KEY REFERENCES NGHESI(MANGHESI),
MABAIHAT CHAR(15) FOREIGN KEY REFERENCES BAIHAT(MABAIHAT),
THONGTINSANGTAC NVARCHAR(15) 
CHECK (THONGTINSANGTAC = N'PHẦN LỜI' OR THONGTINSANGTAC = N'PHẦN NHẠC' OR THONGTINSANGTAC = N'CẢ HAI'),
PRIMARY KEY(MANS,MABAIHAT))
--BẢNG 10
CREATE TABLE TINHTHANH(
MATINHTHANH CHAR(15) PRIMARY KEY,
TENTINHTHANH NVARCHAR(15) NOT NULL UNIQUE)
--BẢNG 11
CREATE TABLE NHASANXUAT(
MANSX CHAR(15) PRIMARY KEY,
TENNSX NVARCHAR(20))
--BẢNG 12
CREATE TABLE KENHTRUYENHINH(
MAKTH CHAR(15) PRIMARY KEY,
TENKENH NVARCHAR(20) NOT NULL)
--BẢNG 13

CREATE TABLE MUATHI(
MAMUATHI CHAR(15) PRIMARY KEY CONSTRAINT IDMUATHI DEFAULT DBO.AUTO_IDMUATHI(),
NGAYBD DATE,
NGAYKT DATE,
GIAITHUONG NVARCHAR(4000),
DIADIEMVNH NVARCHAR(20),
DIADIEMVBK NVARCHAR(20),
DIADIEMVGL NVARCHAR(20),
MAGIAMDOCAN CHAR(15),
MAGIAMKHAO1 CHAR(15),
MAGIAMKHAO2 CHAR(15),
MAGIAMKHAO3 CHAR(15),
MAMC CHAR(15) FOREIGN KEY REFERENCES NGHESI(MANGHESI),
)

--FUNCTION
CREATE FUNCTION AUTO_IDMUATHI()
RETURNS VARCHAR(5)
AS
BEGIN
	DECLARE @IDMUATHI VARCHAR(5)
	IF (SELECT COUNT(MAMUATHI) FROM MUATHI) = 0
		SET @IDMUATHI = '0'
	ELSE
		SELECT @IDMUATHI = MAX(RIGHT(MAMUATHI, 3)) FROM MUATHI
		SELECT @IDMUATHI = CASE
			WHEN @IDMUATHI >= 0 and @IDMUATHI < 9 THEN 'MT00' + CONVERT(CHAR, CONVERT(INT, @IDMUATHI) + 1)
			WHEN @IDMUATHI >= 9 THEN 'MT0' + CONVERT(CHAR, CONVERT(INT, @IDMUATHI) + 1)
		END
	RETURN @IDMUATHI
END
--CHƯA LÀM ĐƯỢC TỰ ĐỘNG BẢNG 13--
--BẢNG 14
CREATE TABLE GIUBANQUYEN(
MAMUATHI CHAR(15) FOREIGN KEY REFERENCES MUATHI(MAMUATHI),
MANSX CHAR(15) FOREIGN KEY REFERENCES NHASANXUAT(MANSX),
PRIMARY KEY(MAMUATHI,MANSX))
--BẢNG 15
CREATE TABLE PHATSONG(
MAMUATHI CHAR(15) FOREIGN KEY REFERENCES MUATHI(MAMUATHI),
MAKTH CHAR(15) FOREIGN KEY REFERENCES KENHTRUYENHINH(MAKTH),
THONGTIN NVARCHAR(15) CHECK (THONGTIN = N'BÁN KẾT' OR THONGTIN = N'GALA' OR THONGTIN = N'CẢ HAI'),
PRIMARY KEY(MAMUATHI,MAKTH))
--BẢNG 16
CREATE TABLE DBO.VONGTHI(
STTVT INT IDENTITY(1,1) ,
MAMUATHI CHAR(15) FOREIGN KEY REFERENCES MUATHI(MAMUATHI),
TENVT NVARCHAR(20),
THOIGIANBD DATE,
THOIGIANKT DATE,
CHECK (THOIGIANBD < THOIGIANKT),
PRIMARY KEY(STTVT,MAMUATHI))
--BẢNG 17	
CREATE TABLE DBO.THISINHTG(
STTVT INT IDENTITY(1,1),
MAMUATHI CHAR(15) FOREIGN KEY REFERENCES MUATHI(MAMUATHI),
MATHISINH CHAR(15) FOREIGN KEY REFERENCES  THISINH(MATHISINH),
KETQUA CHAR(10) DEFAULT  -1 ,
  PRIMARY KEY(STTVT,MAMUATHI,MATHISINH))
 --BẢNG 18
 CREATE TABLE DBO.VONGTHUGIONG(
 STTVT INT IDENTITY(1,1),
 MAMUATHI CHAR(15) FOREIGN KEY REFERENCES MUATHI(MAMUATHI),
 MATINHTHANH CHAR(15) FOREIGN KEY REFERENCES TINHTHANH(MATINHTHANH),
 DIADIEM NVARCHAR(20),
 PRIMARY KEY(MAMUATHI,STTVT))
 --BẢNG 19
 CREATE TABLE VONGTHUGIONGTS(
 STTVT INT FOREIGN KEY REFERENCES VONGTHUGIONG(STTVT),
 MAMUATHI CHAR(15) FOREIGN KEY REFERENCES VONGTHUGIONG(MAMUATHI),
 MATHISINH CHAR(15) FOREIGN KEY REFERENCES  THISINH(MATHISINH),)
 ---CHỖ NÀY MÀU ĐỎ HK HỈU S NÓ KO ZO KHÓA NGOẠI--
 --BẢNG 20
 
